In [2]:
#vector operation

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

dot_product = np.dot(a,b)
print(dot_product)

32


In [14]:
#cross product
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

cross_product = np.cross(a,b)
print(cross_product)

[-3  6 -3]


In [3]:
#magnitude of vector
a = np.array([2,3])
magnitude = np.linalg.norm(a)
print(magnitude)     #sqrt (2^2 + 3^2)

3.605551275463989


In [5]:
#matrix multiplication
a = np.array([1,2,3])
b = np.array([4,5,6])

result_mult = a@b
print(result_mult)

result1_mult = np.matmul(a,b)
print(result1_mult)

32
32


In [6]:
#transpose of matrix
a = np.array([[1,2,3],[4,5,6]])
transpose_a = a.T
print(transpose_a)

[[1 4]
 [2 5]
 [3 6]]


In [7]:
#determinant of matrix
a = np.array([[1,2],[3,4]])
determinant_a = np.linalg.det(a)
print(determinant_a)

-2.0000000000000004


In [8]:
#inverse of the matrix

# Take 'a' variable as an input
#convert this code into function
a = np.array([[1,2],[3,4]])
inverse_a = np.linalg.inv(a)
print(inverse_a)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
#eigen values and eigen vectors
a = np.array([[1,2],[3,4]])
eigen_values, eigen_vectors = np.linalg.eig(a)
print(eigen_values)
print(eigen_vectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [10]:
#Solving the Linear Equation
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
solution = np.linalg.solve(a,b)  #Ax = b
print(solution)

[-4.   4.5]


In [11]:
#concatenate
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [18]:
#vertical stacking

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
print(c.ndim)



2


In [17]:
#horizontal stacking
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
print(c.ndim)

1


In [16]:
#depth stacking

a = np.array([[1,2], [3,4]])
b = np.array([[4,5], [7,8]])
c = np.dstack((a,b))
print(c.ndim)

3


In [24]:
#spliting arrays
arr = np.array([1,2,3,4,5,6])
split = np.split(arr,3)

print(split)

#vertical split (rows wise adjustment)
a = np.array([[1,2],[3,4],[5,6]])
v_split = np.vsplit(a,3)
print(v_split)

#horiontal split (column wise adjustment)
b = np.array([[1,2,3],[4,5,6]])
h_split = np.hsplit(b,3)
print(h_split)


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [26]:
#tiling and repeating
x = np.array([1,2,3])
tile = np.tile(x,(2,3))
print(tile)

repeat = np.repeat(x,3)
print(repeat)

[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]
[1 1 1 2 2 2 3 3 3]


In [28]:
#Pandas library
import pandas as pd

df = pd.read_csv('data.csv', delimiter=';')
print(df)

    Username   Identifier First name Last name
0   booker12         9012     Rachel    Booker
1     grey07         2070      Laura      Grey
2  johnson81         4081      Craig   Johnson
3  jenkins46         9346       Mary   Jenkins
4    smith79         5079      Jamie     Smith


In [29]:
df_excel =pd.read_excel("data.xls")
print(df_excel)

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548


In [30]:
import json
df_json = pd.read_json("data.json")
print(df_json)

                                                    menu
id                                                  file
value                                               File
popup  {'menuitem': [{'value': 'New', 'onclick': 'Cre...


In [31]:
import sqlite3

conn = sqlite3.connect("data.db")
df_sqlite = pd.read_sql_query("SELECT * FROM Car_Parts", conn)
print(df_sqlite)

   part_id       part_name  manufacture_plant_id manufacture_start_date  \
0        1     2.6L Engine                     1             2012-08-12   
1        2     3.0L Engine                     2             2012-07-10   
2        3     2.4L Engine                     5             2012-08-12   
3        4  Jetrag 6 Speed                     5             2012-02-11   
4        5      Bose Audio                     1             2014-08-02   
5        6     4WD Chassis                     2             2000-08-29   
6        7     2WD Chassis                     2             2005-12-20   

  manufacture_end_date  part_recall  
0           2013-08-12            0  
1           2017-02-20            0  
2           2013-08-12            0  
3           2013-08-12            0  
4           2015-03-12            0  
5           2017-05-12            0  
6           2017-11-01            0  


In [33]:
chunksize = 200

for chunk in pd.read_csv("data.csv", delimiter=';', chunksize=chunksize):
    print(chunk.head())  #first 5 rows / lines


    Username   Identifier First name Last name
0   booker12         9012     Rachel    Booker
1     grey07         2070      Laura      Grey
2  johnson81         4081      Craig   Johnson
3  jenkins46         9346       Mary   Jenkins
4    smith79         5079      Jamie     Smith


In [35]:
#optimize memory usage by converting data types
df['Username'] = df['Username'].astype('category')

print(df)


    Username   Identifier First name Last name
0   booker12         9012     Rachel    Booker
1     grey07         2070      Laura      Grey
2  johnson81         4081      Craig   Johnson
3  jenkins46         9346       Mary   Jenkins
4    smith79         5079      Jamie     Smith


In [4]:
import os
import glob
import shutil

# Define backup folder name
backup_folder = "backup_folder"

# Ensure the backup folder exists
os.makedirs(backup_folder, exist_ok=True)

# Get all CSV files in the current directory
csv_files = glob.glob("*.csv")

# Copy each CSV file to the backup folder
for csv_file in csv_files:
    shutil.copy(csv_file, os.path.join(backup_folder, csv_file))

print(f"Successfully backed up {len(csv_files)} files to '{backup_folder}'.")


Successfully backed up 1 files to 'backup_folder'.


In [5]:
# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', None], 'Age': [25, 30, 35, None], 'Salary': [50000, 60000, None, 70000]}
df = pd.DataFrame(data)
# Preview dataset
print(df.head())



      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie  35.0      NaN
3     None   NaN  70000.0


In [38]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    3 non-null      object 
 1   Age     3 non-null      float64
 2   Salary  3 non-null      float64
dtypes: float64(2), object(1)
memory usage: 228.0+ bytes
None


In [40]:
print(df.dtypes)

Name       object
Age       float64
Salary    float64
dtype: object


In [46]:
# print(df.head(2))
# print(df.tail(2))
print(df.sample(2))

      Name   Age   Salary
2  Charlie  35.0      NaN
3     None   NaN  70000.0
      Name   Age   Salary
0    Alice  25.0  50000.0
2  Charlie  35.0      NaN


In [48]:
# print(df.isnull().sum) #missing values
print(df.duplicated().sum)
boxplot = df.boxplot() #checking outliers

<bound method Series.sum of 0    False
1    False
2    False
3    False
dtype: bool>


In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    "A": [1, 2, None, 4],
    "B": [None, 3, 4, 5],
    "C": ["X", "Y", None, "Z"],  
}

df = pd.DataFrame(data)

# Remove missing values
print(df.dropna())

df_filled = df.fillna(df.mean(numeric_only=True))  

print(df_filled)


     A    B  C
1  2.0  3.0  Y
3  4.0  5.0  Z
          A    B     C
0  1.000000  4.0     X
1  2.000000  3.0     Y
2  2.333333  4.0  None
3  4.000000  5.0     Z


In [10]:
import pandas as pd

data = {
    "A": [1, 2, None, 4],
    "B": [None, 3, 4, 5],
    "C": ["X", "Y", None, "Z"],  
}

df = pd.DataFrame(data)

df_numeric = df.apply(pd.to_numeric, errors="coerce")

# Compute correlation
print(df_numeric.corr())


     A    B   C
A  1.0  1.0 NaN
B  1.0  1.0 NaN
C  NaN  NaN NaN


In [12]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Alice", "Bob", "Charlie"],
    "Age": [25, 30, 27, 35, 40],
    "Salary": [50000, 60000, 52000, 65000, 70000],
}

df = pd.DataFrame(data)

# Group by 'Name' and compute the mean for numeric columns
print(df.groupby("Name", as_index=False).mean(numeric_only=True))


      Name   Age   Salary
0    Alice  26.0  51000.0
1      Bob  32.5  62500.0
2  Charlie  40.0  70000.0


In [13]:
import pandas as pd
# Sample DataFrame with missing values and duplicates
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Alice'],
    'Age': [25, 30, 35, 40, 45, None],  # Notice missing value for Age
    'Salary': [50000, 60000, 70000, 80000, None, 50000]  # Notice missing value for Salary
}
# Create DataFrame
df = pd.DataFrame(data)
# Display original DataFrame
print("Original DataFrame:")
print(df)
# Remove missing values (drop rows with any NaN values)
df_cleaned = df.dropna()
print("\nDataFrame After Dropping Missing Values:")
print(df_cleaned)
# Fill missing values with the mean of the column (only for numeric columns)
df_filled = df.copy()
df_filled['Salary'] = df_filled['Salary'].fillna(df_filled['Salary'].mean())
df_filled['Age'] = df_filled['Age'].fillna(df_filled['Age'].mean())
print("\nDataFrame After Filling Missing Values with Mean:")
print(df_filled)
# Remove duplicate rows (based on all columns)
df_unique = df.drop_duplicates()
print("\nDataFrame After Removing Duplicates:")
print(df_unique)
# Change the data type of 'Age' column to Int64 (nullable integer type)
df['Age'] = df['Age'].astype('Int64')  # Nullable integer type
print("\nDataFrame After Changing Data Type of 'Age' to Int64:")



Original DataFrame:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie  35.0  70000.0
3    David  40.0  80000.0
4      Eva  45.0      NaN
5    Alice   NaN  50000.0

DataFrame After Dropping Missing Values:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie  35.0  70000.0
3    David  40.0  80000.0

DataFrame After Filling Missing Values with Mean:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie  35.0  70000.0
3    David  40.0  80000.0
4      Eva  45.0  62000.0
5    Alice  35.0  50000.0

DataFrame After Removing Duplicates:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie  35.0  70000.0
3    David  40.0  80000.0
4      Eva  45.0      NaN
5    Alice   NaN  50000.0

DataFrame After Changing Data Type of 'Age' to Int64:


In [53]:
import pandas as pd
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Alice'],
    'Age': [25, 30, 35, 40, 45, 25],  # Alice appears twice
    'Salary': [50000, 60000, 70000, 80000, 75000, 50000]
}
# Create DataFrame
df = pd.DataFrame(data)
# Checking Correlations between numeric columns (excluding 'Name')
print("Correlation Matrix:")
print(df[['Age', 'Salary']].corr())  # Only pass numeric columns for correlation calculation
# Grouping by 'Name' and calculating the mean of other columns
print("\nGrouped Data (Mean of Age and Salary by Name):")
print(df.groupby('Name', as_index=False).mean())



Correlation Matrix:
             Age    Salary
Age     1.000000  0.939948
Salary  0.939948  1.000000

Grouped Data (Mean of Age and Salary by Name):
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie  35.0  70000.0
3    David  40.0  80000.0
4      Eva  45.0  75000.0
